language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install -q gitversion
  - pip install -q .
  - pip install -q coveralls
script:
  - coverage run --source=django_autoconfig setup.py test
after_success:
  - coveralls
