language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
- pypy3
env:
- DJANGO=1.4.15
- DJANGO=1.6.7
- DJANGO=1.7
install:
- pip install -q gitversion
- pip install -q Django==$DJANGO
- pip install -q .
- pip install -q coveralls
script:
- python setup.py test
after_success:
- coveralls
matrix:
  exclude:
  - python: 2.6
    env: DJANGO=1.7
  - python: 3.2
    env: DJANGO=1.4.15
  - python: 3.3
    env: DJANGO=1.4.15
  - python: pypy3
    env: DJANGO=1.4.15
deploy:
  provider: pypi
  user: LeaChim
  password:
    secure: IuIoDvmYRKjnQQ9wYSPSfKDgG/+8/nDqTj3KUacHt8XCKbjVcbKxsPKz76Zr214iVTqDQUt35w7wIENJSYP0LaHQ42TekwF+TtDcifSzgvQpxyJ0sP9IjqNHaJ6oHa/XXJJWWQjypFLOOUDSMW8t6+dKcrQp/vHctHvVbP1gECA=
  distributions: "sdist bdist_wheel"
  on:
    all_branches: true
    repo: mikebryant/django-autoconfig
    tags: true
    condition: "$DJANGO = 1.7"
